#!/usr/bin/env python3
"""
API Key Setup Script for SSIS to PySpark Converter
Helps users configure their API keys for LLM features.
"""

import os
import getpass
from pathlib import Path

def setup_api_keys():
    """Interactive setup for API keys."""
    print("\n" + "="*60)
    print("SSIS to PySpark Converter - API Key Setup")
    print("="*60 + "\n")
    
    print("This tool uses AI for advanced code validation and refinement.")
    print("You can use either OpenAI or Google Gemini (or both).")
    print()
    
    # Create .env file
    env_file = Path('.env')
    
    # Check if .env already exists
    existing_keys = {}
    if env_file.exists():
        with open(env_file, 'r') as f:
            for line in f:
                if '=' in line and not line.strip().startswith('#'):
                    key, value = line.strip().split('=', 1)
                    existing_keys[key] = value
    
    print("Current API key status:")
    print(f"  OpenAI: {'✅ Set' if existing_keys.get('OPENAI_API_KEY') else '❌ Not set'}")
    print(f"  Gemini: {'✅ Set' if existing_keys.get('GEMINI_API_KEY') else '❌ Not set'}")
    print()
    
    # Prompt for provider choice
    print("Which AI provider would you like to configure?")
    print("1. OpenAI (GPT-4)")
    print("2. Google Gemini (Free tier available)")
    print("3. Both")
    print("4. Skip (use rule-based conversion only)")
    
    choice = input("\nEnter your choice (1-4): ").strip()
    
    new_keys = {}
    
    if choice in ['1', '3']:
        print("\n🔑 OpenAI API Key Setup")
        print("Get your API key from: https://platform.openai.com/api-keys")
        openai_key = getpass.getpass("Enter your OpenAI API key: ").strip()
        if openai_key:
            new_keys['OPENAI_API_KEY'] = openai_key
            new_keys['DEFAULT_LLM_PROVIDER'] = 'openai'
    
    if choice in ['2', '3']:
        print("\n🔑 Google Gemini API Key Setup")
        print("Get your API key from: https://makersuite.google.com/app/apikey")
        gemini_key = getpass.getpass("Enter your Gemini API key: ").strip()
        if gemini_key:
            new_keys['GEMINI_API_KEY'] = gemini_key
            if 'DEFAULT_LLM_PROVIDER' not in new_keys:
                new_keys['DEFAULT_LLM_PROVIDER'] = 'gemini'
    
    if choice == '4':
        print("✅ Skipping API key setup. Using rule-based conversion only.")
        return
    
    if not new_keys:
        print("❌ No API keys provided. Using rule-based conversion only.")
        return
    
    # Write .env file
    with open(env_file, 'w') as f:
        f.write("# SSIS to PySpark Converter - Environment Variables\n")
        f.write("# Generated by setup_api_keys.py\n\n")
        
        for key, value in new_keys.items():
            f.write(f"{key}={value}\n")
        
        # Keep existing keys that weren't updated
        for key, value in existing_keys.items():
            if key not in new_keys:
                f.write(f"{key}={value}\n")
    
    print(f"\n✅ API keys saved to {env_file}")
    print("You can now run the converter with AI features enabled!")
    print("\nUsage:")
    print("  python ssis_to_pyspark_app.py input/package.dtsx")
    print("  # or")
    print("  ssis_to_pyspark_converter.exe input/package.dtsx")

if __name__ == '__main__':
    setup_api_keys()
